apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: cnr-devx-workshop
spec:
  portal:
    registration:
      type: anonymous
    ingress:
      class: contour-external
  workshops:
  - name: cnr-devx-workshop
    capacity: 2
    reserved: 0
    expires: 60m
    orphaned: 5m
