apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: cnr-devx-workshop
spec:
  title: Test workshop for DevX TSL meeting
  description: A workshop for the DevX TSL discussion
  vendor: eduk8s.io
  authors:
  - Anand Rao 
  - Craig Olrich 
  difficulty: intermediate
  duration: 15m
  url: https://github.com/colrich/cnr-fundamentals-workshop
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
#    image: honnuanand/cnr-dev-fundamentals:0.3
#    image: quay.io/eduk8s/base-environment:master
#    image: olrich/cnr-workshop:0.1
    image: ghcr.io/clue2solve/knative-workshop-eduk8s:latest
    files: github.com/colrich/cnr-fundamentals-workshop
  session:
    namespaces:
      budget: medium
      limits:
        min:
          cpu: 25m
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
